# Generated by Django 3.2.7 on 2021-12-14 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
