# Generated by Django 3.2.7 on 2021-12-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0004_remove_task_added_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='added_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
