# Generated by Django 3.2.7 on 2021-12-28 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0005_task_added_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='multiple_select_language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programming_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskapp.programminglanguage')),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskapp.tasktype')),
            ],
        ),
    ]
