# Generated by Django 3.2.7 on 2021-12-28 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0006_multiple_select_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiple_select_language',
            name='task_type',
        ),
    ]
