# Generated by Django 3.2.7 on 2021-12-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0007_remove_multiple_select_language_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiple_select_language',
            name='type_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
