# Generated by Django 3.2.7 on 2021-12-28 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0008_multiple_select_language_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiple_select_language',
            name='type_name',
        ),
    ]
