# Generated by Django 3.2.7 on 2021-12-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0010_multiple_select_language_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiple_select_language',
            name='multiple_language',
            field=models.BooleanField(default=False),
        ),
    ]
