# Generated by Django 3.2.7 on 2021-12-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0012_remove_multiple_select_language_multiple_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype',
            name='multiple_language',
            field=models.BooleanField(default=False),
        ),
    ]
