# Generated by Django 3.2.7 on 2022-01-13 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0013_tasktype_multiple_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiple_select_language',
            name='task_type',
        ),
        migrations.AddField(
            model_name='tasktype',
            name='multiple_select',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskapp.multiple_select_language'),
        ),
    ]
