# Generated by Django 3.2.7 on 2022-01-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0017_remove_reporting_programming_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporting',
            name='duration_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='duration_till',
            field=models.DateField(blank=True, null=True),
        ),
    ]
