# Generated by Django 3.2.7 on 2022-01-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0018_auto_20220119_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporting',
            name='duration_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='duration_till',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
