# Generated by Django 3.2.7 on 2022-01-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0019_auto_20220120_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporting',
            name='duration_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='duration_till',
            field=models.DateField(blank=True, null=True),
        ),
    ]
