# Generated by Django 3.2.7 on 2022-01-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0021_auto_20220124_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporting',
            name='user',
        ),
        migrations.AddField(
            model_name='reporting',
            name='reported_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
