# Generated by Django 3.2.7 on 2022-02-02 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0024_auto_20220131_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigned_system_detail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='taskapp.user', unique=True),
        ),
    ]
