# Generated by Django 3.2.7 on 2022-02-16 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0027_attendence_detail_attendence'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='mark_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Casual', 'Casual'), ('Study', 'Study'), ('Maternity', 'Maternity'), ('Medical ', 'Medical'), ('Quarantine ', 'Quarantine'), ('Emergency ', 'Emergency')], max_length=255)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('reason', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskapp.user')),
            ],
        ),
    ]
