# Generated by Django 3.2.7 on 2022-02-22 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0030_holidays'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Holidays',
        ),
    ]
