# Generated by Django 3.2.7 on 2022-02-28 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0032_holidays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidays',
            name='holidays_count',
        ),
    ]
