# Generated by Django 3.2.7 on 2022-02-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0033_remove_holidays_holidays_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidays',
            name='to_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
