# Generated by Django 3.2.7 on 2022-02-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0034_alter_holidays_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidays',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
