# Generated by Django 3.2.7 on 2022-03-04 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0035_alter_holidays_to_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
