# Generated by Django 3.2.7 on 2022-03-09 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0036_delete_leave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='mark_leave',
        ),
    ]
