# Generated by Django 3.2.7 on 2022-03-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0037_remove_attendence_mark_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='absent',
            field=models.BooleanField(default=False),
        ),
    ]
