# Generated by Django 3.2.7 on 2022-03-09 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0038_attendence_absent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail_attendence',
            name='attendence',
        ),
        migrations.RemoveField(
            model_name='detail_attendence',
            name='user',
        ),
        migrations.DeleteModel(
            name='Attendence',
        ),
        migrations.DeleteModel(
            name='Detail_attendence',
        ),
    ]
