# Generated by Django 3.2.7 on 2022-05-23 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0040_attendence_detail_attendence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigned_system_detail',
            name='system_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskapp.system_detail'),
        ),
        migrations.AlterField(
            model_name='assigned_system_detail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskapp.user'),
        ),
    ]
