# Generated by Django 3.2.7 on 2022-05-24 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0041_auto_20220523_1249'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Holidays',
        ),
    ]
