# Generated by Django 3.2.7 on 2022-05-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0044_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leave',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
