# Generated by Django 3.2.7 on 2022-06-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0046_auto_20220614_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_detail',
            name='status',
            field=models.CharField(default='Free', max_length=50),
        ),
    ]
