# Generated by Django 3.2.7 on 2022-07-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0050_addevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addevent',
            name='description',
            field=models.TextField(max_length=240),
        ),
    ]
