# Generated by Django 3.2.7 on 2022-07-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0051_alter_addevent_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addevent',
            name='photo',
        ),
        migrations.CreateModel(
            name='Event_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='event_images')),
                ('addevent', models.ManyToManyField(to='taskapp.AddEvent')),
            ],
        ),
    ]
