# Generated by Django 3.2.7 on 2022-07-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0054_alter_event_photo_addevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_photo',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
