# Generated by Django 3.2.7 on 2022-07-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0055_event_photo_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store_token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('token', models.TextField()),
            ],
        ),
    ]
