# Generated by Django 3.2.7 on 2022-07-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0057_notification_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_token',
            name='device',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store_token',
            name='os',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
