"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-am^e$fi82!y9(ey@@34ls)ab6eg0g4b7$!cj6p5of+5@m5z@$o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'taskapp',
    'import_export',
    'rangefilter',
    'dashboardapp',
    'indexapp',
    'admindashboard',
    'projectapp',
    'django_crontab',
    'notification',
    'django_user_agents',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {
                'editable': 'taskapp.templatetags.CustomTaskappTags',

            }
        },
    },
]
X_FRAME_OPTIONS = 'SAMEORIGIN'
WSGI_APPLICATION = 'core.wsgi.application'
#
# # Database
# # https://docs.djangoproject.com/en/3.2/ref/settings/#databases
# #
# # LOCAL
# # #
# # #
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}




# PRODUCTION
# DATABASES = {

#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'workeasy',
#         'USER': 'root',
#         'PASSWORD':'okhotsk123',
#         'HOST': '',
#         'PORT': '',
     
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (BASE_DIR / 'static_cdn',)
STATIC_ROOT = os.path.join(BASE_DIR, '/static')

# Media (USer Uploaded Files)

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'taskapp.user'

LOGOUT_REDIRECT_URL = '/'

# if DEBUG:
#     INTERNAL_IPS = ('127.0.0.1', 'localhost',)
#     MIDDLEWARE += (
#         'debug_toolbar.middleware.DebugToolbarMiddleware',
#     )

#     INSTALLED_APPS += (
#         'debug_toolbar',
#     )

#     DEBUG_TOOLBAR_PANELS = [
#         'debug_toolbar.panels.versions.VersionsPanel',
#         'debug_toolbar.panels.timer.TimerPanel',
#         'debug_toolbar.panels.settings.SettingsPanel',
#         'debug_toolbar.panels.headers.HeadersPanel',
#         'debug_toolbar.panels.request.RequestPanel',
#         'debug_toolbar.panels.sql.SQLPanel',
#         'debug_toolbar.panels.staticfiles.StaticFilesPanel',
#         'debug_toolbar.panels.templates.TemplatesPanel',
#         'debug_toolbar.panels.cache.CachePanel',
#         'debug_toolbar.panels.signals.SignalsPanel',
#         'debug_toolbar.panels.logging.LoggingPanel',
#         'debug_toolbar.panels.redirects.RedirectsPanel',
#     ]

#     DEBUG_TOOLBAR_CONFIG = {
#         # 'INTERCEPT_REDIRECTS': False,
#         'SHOW_TOOLBAR_CALLBACK': lambda r: False,
#     }

CRONJOBS = [
    ('*/1 * * * *', 'admindashboard.cron.my_cron_job'),
    ('1 0 * * 1-5', 'admindashboard.cron.create_daily_attendence'),
    ('1 0 * * 0-6', 'admindashboard.cron.birthday_messages'),
    ('30,59 9 * * 1-5', 'admindashboard.cron.send'),

]

EMAIL_USE_TLS = True
EMAIL_HOST = 'mail.eoutlooks.com'
EMAIL_HOST_USER = 'bestwishes@visiontrek.in'
EMAIL_HOST_PASSWORD = 'bt123'
EMAIL_PORT = 587



EMAIL_HOST_USER1 = 'uptask@visiontrek.in'
EMAIL_HOST_PASSWORD1 = 'upta23'


