# Generated by Django 3.2.7 on 2021-12-14 04:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField(default='')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
                ('started', models.BooleanField(blank=True, default=False, null=True)),
                ('started_on', models.DateTimeField()),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
